apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: hello-world-local
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: alpine:latest
      command: ["echo"]
      args: ["foo"]
